dist: xenial
language: python
sudo: false
env:
  - PYTHON_VERSION=3.6 COVER_PACKAGE="qp_meta/filter qp_meta/trim qp_meta/sortmerna"
before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda3/bin:$PATH
  # Update conda itself
  - conda update --yes conda
install:
  # installing qiita environment
  - conda config --add channels anaconda
  - conda config --add channels conda-forge
  - conda config --add channels bioconda
  - travis_retry conda create -q --yes -n qiita python=3.6 pip libgfortran numpy nginx cython
  - source activate qiita
  - pip install sphinx sphinx-bootstrap-theme coveralls
  - pip install https://github.com/biocore/qiita/archive/dev.zip --no-binary redbiom
  - sed 's/PORT = 7777/PORT = 6379/g' ${HOME}/miniconda3/envs/qiita/lib/python3.6/site-packages/qiita_core/support_files/config_test.cfg > config_test.cfg
  - export QIITA_CONFIG_FP=${PWD}/config_test.cfg
  # starting nginx
  - mkdir /home/travis/miniconda3/envs/qiita/var/run/nginx/
  - wget https://github.com/biocore/qiita/archive/dev.zip -O qiita-dev.zip
  - unzip qiita-dev.zip
  - nginx -c ${PWD}/qiita-dev/qiita_pet/nginx_example.conf
  - qiita-env make --no-load-ontologies
  - source deactivate
  # installing qp-meta
  - conda create --yes -n qp-meta biom-format bowtie2 sortmerna=2.1b samtools pigz
  - source activate qp-meta
  - pip install -U pip pip nose flake8
  - pip install sphinx sphinx-bootstrap-theme nose-timer codecov biopython
  - pip install https://github.com/qiita-spots/qiita_client/archive/master.zip
  - pip install atropos
  - export QIITA_SERVER_CERT=$HOME/miniconda3/envs/qiita/lib/python3.6/site-packages/qiita_core/support_files/server.crt
  - pip install .
  - export QC_FILTER_DB_DP=$PWD/qp_meta/filter/databases/
  - export QC_SORTMERNA_DB_DP=$PWD/qp_meta/sortmerna/databases/rRNA_databases/
  - pushd $QC_SORTMERNA_DB_DP
  - for file in $(ls); do gunzip $file; done
  - popd
  # making sure we have the correct software versions
  - bowtie2_version=`bowtie2 --version`
  - if [[ $bowtie2_version != *"2.4.2"* ]]; then echo "wrong bowtie2 version", $bowtie2_version; exit 1; fi
  - configure_meta --env-script "source activate qp-meta" --server-cert $QIITA_SERVER_CERT
before_script:
  - source activate qiita
  - qiita plugins update
  - supervisord -c ${PWD}/qiita-dev/qiita_pet/supervisor_example.conf
  - sleep 10 # give enough time to the webserver to start
  - cat /tmp/supervisord.log
script:
  - source activate qp-meta
  - travis_wait 40 nosetests $COVER_PACKAGE --with-doctest --with-coverage --with-timer -vv --cover-package=$COVER_PACKAGE
  - flake8 qp_meta setup.py scripts
addons:
  postgresql: "9.5"
services:
  - redis-server
  - postgresql
after_success:
  - codecov
  - qiita-env drop
after_failure:
  - kill $QIITA_PID
  - qiita-env drop
